<?php

return [
    'articles' => [
        'verblijf-bij-ongehuwde-partner' => [
            'title' => 'Verblijf bij (ongehuwde) partner',
            'summary' => 'MVV/TEV-procedure en inkomenseisen voor partners.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/verblijf-bij-ongehuwde-partner.php',
        'keywords' => ['partner', 'echtgenoot', 'mvv', 'huwelijk'],
    ],
        'verblijfsaanvraag-overige-familieleden' => [
            'title' => 'Verblijfsaanvraag overige familieleden',
            'summary' => 'Artikel 8 EVRM-traject voor ouders en andere familieleden.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/verblijfsaanvraag-overige-familieleden.php',
        'keywords' => ['familie', 'ouders', 'artikel 8', 'EVRM'],
    ],
        'verblijf-bij-minderjarige-nederlands-kind-chavez-vilchez' => [
            'title' => 'Verblijf minderjarig Nederlands kind',
            'summary' => 'Chavez-Vilchez bescherming voor verzorgende ouders.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/verblijf-bij-minderjarige-nederlands-kind-chavez-vilchez.php',
        'keywords' => ['kind', 'chavez', 'ouder', 'nederlands kind'],
    ],
        'machtiging-voorlopig-verblijf-mvv' => [
            'title' => 'Machtiging voorlopig verblijf (MVV)',
            'summary' => 'De volledige MVV-route met documenten en termijnen.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/machtiging-voorlopig-verblijf-mvv.php',
        'keywords' => ['mvv', 'machtiging', 'paspoort', 'visum'],
    ],
        'arbeid' => [
            'title' => 'Arbeid',
            'summary' => 'GVVA en werkvergunningen voor werknemers van buiten de EU.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/arbeid.php',
        'keywords' => ['werkvergunning', 'gvva', 'arbeid', 'werkgever'],
    ],
        'verblijfsvergunning-als-zelfstandige-ondernemer' => [
            'title' => 'Zelfstandige ondernemer',
            'summary' => 'Voorwaarden voor zelfstandigen, start-ups en investeerders.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/verblijfsvergunning-als-zelfstandige-ondernemer.php',
        'keywords' => ['zzp', 'ondernemer', 'startup', 'investering'],
    ],
        'studeren-in-nederland' => [
            'title' => 'Studeren in Nederland',
            'summary' => 'Vergunningen voor studenten en zoekjaar-kandidaten.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/studeren-in-nederland.php',
        'keywords' => ['studie', 'zoekjaar', 'studentenvisum'],
    ],
        'remigreren-naar-nederland-oud-nederlanders' => [
            'title' => 'Remigreren naar Nederland',
            'summary' => 'Opties voor oud-Nederlanders die willen terugkeren.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/remigreren-naar-nederland-oud-nederlanders.php',
        'keywords' => ['remigratie', 'oud-nederlander', 'terugkeer'],
    ],
        'verblijfsvergunning-medische-gronden' => [
            'title' => 'Medische behandeling',
            'summary' => 'Aanvragen op medische gronden en noodzakelijke bewijsstukken.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/verblijfsvergunning-medische-gronden.php',
        'keywords' => ['medisch', 'behandeling', 'arts', 'zorg'],
    ],
        'verblijfsvergunning-onbepaalde-tijd-aanvragen' => [
            'title' => 'Verblijfsvergunning onbepaalde tijd',
            'summary' => 'Checklist voor duurzame vestiging en bewijs van inburgering.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/verblijfsvergunning-onbepaalde-tijd-aanvragen.php',
        'keywords' => ['permanent', 'duurzaam verblijf', 'onbepaalde tijd'],
    ],
        'gezinshereniging' => [
            'title' => 'Gezinshereniging in Nederland',
            'summary' => 'Checklist en aandachtspunten voor gezinsleden.',
            'category' => 'Verblijfsvergunning regulier',
        'file' => __DIR__ . '/info/gezinshereniging.php',
        'keywords' => ['gezin', 'partner', 'kind', 'samenvoegen'],
    ],
        'chavez-vilchez' => [
            'title' => 'Chavez-Vilchez procedure',
            'summary' => 'Stappenplan voor ouders van Nederlandse kinderen.',
            'category' => 'Verblijfsprocedures EU',
        'file' => __DIR__ . '/info/chavez-vilchez.php',
        'keywords' => ['chavez', 'ouder', 'eu-recht'],
    ],
        'eu-burger-en-gezinsleden' => [
            'title' => 'EU-burger en gezinsleden',
            'summary' => 'Verblijfsrechten voor Unieburgers en familie.',
            'category' => 'Verblijfsprocedures EU',
        'file' => __DIR__ . '/info/eu-burger-en-gezinsleden.php',
        'keywords' => ['eu-burger', 'vrij verkeer', 'gezinsleden'],
    ],
        'toetsing-aan-eu-recht-belgie-route' => [
            'title' => 'Toetsing aan EU-recht (België-route)',
            'summary' => 'Wanneer de België-route een oplossing biedt voor partners.',
            'category' => 'Verblijfsprocedures EU',
        'file' => __DIR__ . '/info/toetsing-aan-eu-recht-belgie-route.php',
        'keywords' => ['belgie route', 'eu-route', 'vrij verkeer'],
    ],
        'EUprocedure' => [
            'title' => 'Chavez-Vilchez & EU-verblijfsrechten',
            'summary' => 'Kader en gevolgen van EU-recht voor gezinnen.',
            'category' => 'Verblijfsprocedures EU',
        'file' => __DIR__ . '/info/EUprocedure.php',
        'keywords' => ['eu-procedure', 'chavez', 'verblijfsrechten'],
    ],
        'schengenvisum' => [
            'title' => 'Schengenvisum',
            'summary' => 'Eisen, documenten en behandelingsduur voor kort verblijf.',
            'category' => 'Visum kort verblijf',
        'file' => __DIR__ . '/info/schengenvisum.php',
        'keywords' => ['visum', 'schengen', 'kort verblijf'],
    ],
        'spoed-visum' => [
            'title' => 'Spoed visum',
            'summary' => 'Wanneer spoed mogelijk is en welke bewijzen nodig zijn.',
            'category' => 'Visum kort verblijf',
        'file' => __DIR__ . '/info/spoed-visum.php',
        'keywords' => ['spoed', 'visum', 'urgent'],
    ],
        'bezwaarschrift-tegen-afgewezen-schengenvisum' => [
            'title' => 'Bezwaarschrift Schengenvisum',
            'summary' => 'Zo pakt u een afwijzing van een visumaanvraag aan.',
            'category' => 'Visum kort verblijf',
        'file' => __DIR__ . '/info/bezwaarschrift-tegen-afgewezen-schengenvisum.php',
        'keywords' => ['bezwaar', 'afwijzing', 'schengen', 'visum'],
    ],
        'nederlander-worden' => [
            'title' => 'Nederlander worden',
            'summary' => 'Naturalisatie- en optieprocedure in begrijpelijke taal.',
            'category' => 'Nederlanderschap',
        'file' => __DIR__ . '/info/nederlander-worden.php',
        'keywords' => ['naturalisatie', 'paspoort', 'nationaliteit'],
    ],
        'het-verliezen-van-de-nederlandse-nationaliteit' => [
            'title' => 'Verlies Nederlandse nationaliteit',
            'summary' => 'Voorkomen of herstellen van een verlies van nationaliteit.',
            'category' => 'Nederlanderschap',
        'file' => __DIR__ . '/info/het-verliezen-van-de-nederlandse-nationaliteit.php',
        'keywords' => ['nationaliteit', 'verlies', 'paspoort'],
    ],
        'nederlanderschap' => [
            'title' => 'Nederlanderschap & naturalisatie',
            'summary' => 'Voorwaarden, bewijsstukken en veelgestelde vragen.',
            'category' => 'Nederlanderschap',
        'file' => __DIR__ . '/info/nederlanderschap.php',
        'keywords' => ['naturalisatie', 'optie', 'nationaliteit'],
    ],
        'intrekking-verblijfsvergunning' => [
            'title' => 'Intrekking verblijfsvergunning',
            'summary' => 'Hoe u zich kunt verweren tegen een voorgenomen intrekking.',
            'category' => 'Intrekking & rechtsmiddelen',
        'file' => __DIR__ . '/info/intrekking-verblijfsvergunning.php',
        'keywords' => ['intrekking', 'vergunning', 'verweer'],
    ],
        'bezwaar-beroep' => [
            'title' => 'Bezwaar en beroep tegen IND-beslissingen',
            'summary' => 'Aanpak en tijdlijn na een afwijzing of intrekking.',
            'category' => 'Intrekking & rechtsmiddelen',
        'file' => __DIR__ . '/info/bezwaar-beroep.php',
        'keywords' => ['bezwaar', 'beroep', 'ind'],
    ],
        'arbeidsmigratie' => [
            'title' => 'Arbeid en ondernemersvisa',
            'summary' => 'Kennismigranten, start-ups en zelfstandigen in één overzicht.',
            'category' => 'Verdiepende dossiers',
        'file' => __DIR__ . '/info/arbeidsmigratie.php',
        'keywords' => ['arbeidsmigrant', 'kennismigrant', 'start-up'],
    ],
        'over-ons' => [
            'title' => 'Over ons',
            'summary' => 'Maak kennis met ons kantoor en onze aanpak.',
            'category' => 'Over ons & contact',
        'file' => __DIR__ . '/info/over-ons.php',
        'keywords' => ['kantoor', 'team', 'werkwijze'],
    ],
        'contact' => [
            'title' => 'Contact',
            'summary' => 'Neem direct contact op voor een gratis intake.',
            'category' => 'Over ons & contact',
        'file' => __DIR__ . '/info/contact.php',
        'keywords' => ['contact', 'intake', 'telefoon'],
    ],
    ],
    'categoryOrder' => [
        'Verblijfsvergunning regulier',
        'Verblijfsprocedures EU',
        'Visum kort verblijf',
        'Nederlanderschap',
        'Intrekking & rechtsmiddelen',
        'Verdiepende dossiers',
        'Over ons & contact',
    ],
];
